Test failure

diff --git a/.github/workflows/npm-checks.yml b/.github/workflows/npm-checks.yml
--- a/.github/workflows/npm-checks.yml
+++ b/.github/workflows/npm-checks.yml
@@ -159,12 +159,9 @@ jobs:
           fi
 
       - name: Report Success/Failure
-        run: |
-          if [ "${{ steps.visual_test.outcome }}" eq "failure" ]
-          then
-            echo ${{ steps.visual_test.outputs }}
-            exit 1
-          fi
+        if: failure() && steps.visual_test.outcome == 'failure'
+        run: exit 1
+        # This is needed as a unique step to allow for image uploads after test:visual fails
 
   lint:
     needs: [install]
